agent:
  speed:
    min_value: 0
    max_value: 1
    options:
      - type: speed-option
        id: speed_1
        value: 0.12

      - type: speed-option
        id: speed_2
        value: 0.28

      - type: speed-option
        id: speed_3
        value: 0.45

      - type: speed-option
        id: speed_4
        value: 0.65

  direction:
    - type: direction-option
      id: direction_1
      radians: 0.0

    - type: direction-option
      id: direction_2
      radians: 1.570796

    - type: direction-option
      id: direction_3
      radians: 3.141592

    - type: direction-option
      id: direction_4
      radians: 4.712389

  influence:
    wind_x_coef: 0.8
    wind_y_coef: 1.2

  battery:
    min_value: 0
    max_value: 1
    speed_coef: -0.020
    wind_x_coef: -0.004
    wind_y_coef: -0.003
    charge_coef: 0.030



  quants:
    x: 52
    y: 28
    b: 10
    v: 4

